### ISSUE TITLE
Please, beutify the repo

### ISSUE THREAD

**Issue by GeekyShiva** [vyaspranjal33/Learn-WebVR#1]
Hi Pranjal,

It would be really nice if you could beautify this repository and make it appealing for the upcoming audience.

Check this : https://github.com/udacity/deep-learning

Cheers

**Comment by vyaspranjal33** [comment]
Hi @GeekyShiva  It's Seems Aleredy beautified

Do you want to beautify Readme ?

**Comment by GeekyShiva** [comment]
Cool I will work over it when I will get some time in near future.

I wish the repo to be easy to use and I just don't end up opening dumb links through it.
Giving it a brief touch-up with content from links and better header-subject relation would complete the task.

**Comment by vyaspranjal33** [comment]
i wish I could do but as i am not familiar with Udacity & its strucutre so its difficult for me to figure out what the hack is going on i hope u get it @GeekyShiva
